# Generated by Django 4.2.1 on 2023-05-13 02:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('url', models.CharField()),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('team', models.CharField()),
                ('role', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('due', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='success.people')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
