# Generated by Django 4.2.2 on 2023-06-26 01:58

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0002_rename_people_person_rename_peoplelog_personlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=200)),
                ('item_id', models.DateField(default=None, null=True)),
                ('body', django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                'db_table': 'search_index',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='personlog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='success.person'),
        ),
    ]
