# Generated by Django 4.2.2 on 2023-06-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0004_create_search_index_view'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""CREATE UNIQUE INDEX ON success_search_index (item_id);""",
            reverse_sql="DROP INDEX success_search_index_item_id_idx;"
        )
    ]
