# Generated by Django 4.2.3 on 2023-07-24 00:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0006_update_search_index_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None),
        ),
        migrations.AlterModelTable(
            name='searchindex',
            table='success_search_index',
        ),
    ]
