# Generated by Django 4.2.3 on 2023-07-27 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0007_alter_project_options_project_order_alter_link_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField()),
                ('system_message', models.TextField()),
                ('request_template', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
