# Generated by Django 4.2.3 on 2023-08-17 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0008_prompttemplate_alter_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('system', models.TextField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
