# Generated by Django 4.2.3 on 2023-08-23 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0009_assistantanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantanswer',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
