# Generated by Django 4.2.3 on 2023-09-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0010_assistantanswer_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchPad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
