# Generated by Django 4.2.3 on 2025-09-03 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0016_add_created_at_to_search_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantanswer',
            options={'ordering': ['-datetime']},
        ),
        migrations.AddField(
            model_name='assistantanswer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='success.assistantanswer'),
        ),
    ]
