# Generated by Django 4.2.3 on 2025-09-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0019_auto_20250903_0212'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS success_assistantanswer CASCADE;",
            reverse_sql="-- No reverse operation for dropping table"
        ),
    ]
