# Generated by Django 4.2.3 on 2025-09-04 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0020_auto_20250903_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('email_date', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_id', models.CharField(max_length=200)),
                ('calendar_name', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Calendar Settings',
            },
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('encrypted_credentials', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Google Credentials',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_email_enabled', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('email_time', models.TimeField(default='07:00')),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='google_credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to='success.googlecredentials'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarsettings',
            unique_together={('google_credentials', 'calendar_id')},
        ),
    ]
