# Generated by Django 4.2.3 on 2025-09-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0020_auto_20250903_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=10),
        )
    ]
