# Generated by Django 4.2.3 on 2025-09-04 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0021_calendaremaillog_calendarsettings_googlecredentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='email_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
