version: '3.9' 

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready -U postgres"
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 5
  frontend:
    image: "ghcr.io/mbseid/success-frontend:main"
    ports:
      - "3000:3000"
    environment:
      - API_HOST=http://backend:8000
    depends_on:
      - backend
  backend:
    image: "ghcr.io/mbseid/success-backend:main"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    depends_on:
      db:
        condition: service_healthy
volumes:
    pgdata: